### ISSUE TITLE
RFC 9285 compat?

### ISSUE THREAD

**Issue by cbrunnkvist** [yurelle/Base45Encoder#1]
Is this code intended to be compatible with the encoding described in https://datatracker.ietf.org/doc/rfc9285/ or is it only a namesake?

**Comment by yurelle** [comment]
I'm sorry dude, I just noticed this ticket just now. Not sure how I missed the notification.

Originally, this was intended to just interface with an internal optimization I found inside the ZXing QR Code library, as I was unaware of the official Base45 standard. However, a few days ago, someone else opened [a ticket about this issue](https://github.com/yurelle/Base45Encoder/issues/2), and after investigating the standard, I rewrote this lib to be compliant with that standard.

v2.0.0 of this lib should be compliant with RFC-9285. I know it's been like 8 months since you opened this ticket, but if you still have need of this lib, it should be good to go now. Let me know if you have any issues.

Again, sorry I missed your ticket.
